name: Charlotte Testing

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [macos-latest, window-latest, ubuntu-latest]
        arm: [x86, arm64]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install Charlotte  # Replace 'Charlotte' with the actual module name if it's a package you've developed
      - name: Test with pytest
        run: |
          pytest --verbose
